<?xml version="1.0"?>
<robot name="jetsoncar" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- X axis direction is forward, Y axis direction is left -->

	<!-- Baseplate related properties -->
	<xacro:property name="baseplate_width" value="0.20" />	
	<xacro:property name="baseplate_length" value="0.50" />	
	<xacro:property name="baseplate_thickness" value="0.0675" />	
	<xacro:property name="baseplate_weight" value="1.000" />	

	<!-- Baseplate -->
	<xacro:macro name="baseplate_geometry">
		<origin xyz="0 0 ${baseplate_thickness/2}" rpy="0 0 0" /> <!-- origin (0,0,0) is in the center of the box, so place the origin of this in the bottom of baseplate -->
		<geometry>
			<box size="${baseplate_length} ${baseplate_width} ${baseplate_thickness}"/> <!-- 50x20x6.75 cm, X-axis is front of vehicle -->
		</geometry>
	</xacro:macro>
    
	<xacro:macro name="baseplate_inertial">
		<origin xyz="0 0 ${baseplate_thickness/2}" rpy="0 0 0" /> <!-- origin (0,0,0) is in the center of the box, so place the origin of this in the bottom of baseplate -->
		<xacro:box_inertial mass="${baseplate_weight}" length="${baseplate_length}" width="${baseplate_width}" height="${baseplate_thickness}" />
	</xacro:macro>

</robot>
